// src/components/Routes/vault/wallet.tsx
import { Fragment } from "react";
import { FormattedMessage, FormattedNumber } from "react-intl";

import currencyClasses from "../../Currency/index.module.css";
import elementsClasses from "../../Elements/index.module.css";
import { Query } from "../../Query";
import { QueryError } from "../../Query/Error";
import { QueryLoading } from "../../Query/Loading";
import { QuerySuccess } from "../../Query/Success";
import { QueryUninitialized } from "../../Query/Uninitialized";

import { classNames } from "../../../features/css/classnames";
import { readAccountWallet } from "../../../features/store/api/read-account-wallet";
import {
  initialState,
  readCurrencies,
} from "../../../features/store/api/read-currencies";

export function VaultWallet() {
  const readCurrenciesResult = readCurrencies.useQuery({});
  const readAccountWalletResult = readAccountWallet.useQuery({});
  return (
    <Fragment>
      <h2>
        <FormattedMessage defaultMessage="Wallet" />
      </h2>
      <Query result={readCurrenciesResult}>
        <QueryUninitialized>Waiting to load currencies...</QueryUninitialized>
        <QueryLoading>Loading currencies...</QueryLoading>
        <QueryError>Failed to load currencies</QueryError>
        <QuerySuccess>
          <Query result={readAccountWalletResult}>
            <ol
              className={classNames(
                elementsClasses["no-margin"],
                elementsClasses["no-padding"]
              )}
              style={{
                columnGap: "1rem",
                columns: "8 24rem",
                maxWidth: "200rem",
              }}
            >
              {(readCurrenciesResult.data ?? initialState).ids.map(
                (currencyId) => (
                  <li
                    className={classNames(currencyClasses["currency"])}
                    key={currencyId}
                  >
                    <h3
                      className={classNames(
                        currencyClasses["currency__name"],
                        elementsClasses["no-margin"]
                      )}
                    >
                      {readCurrenciesResult.data!.entities[currencyId]!.name}
                    </h3>
                    <span
                      className={classNames(
                        currencyClasses["currency__amount"]
                      )}
                    >
                      <QueryUninitialized>-</QueryUninitialized>
                      <QueryLoading>-</QueryLoading>
                      <QueryError>x</QueryError>
                      <QuerySuccess>
                        <FormattedNumber
                          value={
                            readAccountWalletResult.data?.entities[currencyId]
                              ?.value ?? 0
                          }
                          maximumSignificantDigits={3}
                        />
                      </QuerySuccess>
                    </span>
                    <img
                      alt={
                        readCurrenciesResult.data!.entities[currencyId]?.name
                      }
                      className={classNames(currencyClasses["currency__img"])}
                      src={
                        readCurrenciesResult.data!.entities[currencyId]?.icon
                      }
                    />
                    <p
                      className={classNames(
                        currencyClasses["currency__description"],
                        elementsClasses["no-margin"]
                      )}
                    >
                      {
                        readCurrenciesResult.data!.entities[currencyId]!
                          .description
                      }
                    </p>
                  </li>
                )
              )}
            </ol>
          </Query>
        </QuerySuccess>
      </Query>
    </Fragment>
  );
}

// src/routes/vault/wallet/+page.svelte
<script lang="ts">
	import { storeCtx } from '$lib/context';
	import { useQuery } from '$lib/rtk-svelte/hooks.js';
	import { hydrate } from '$lib/store/actions.js';
	import { readAccountWallet } from '$lib/store/api/read-account-wallet.js';
	import { readCurrencies } from '$lib/store/api/read-currencies';

	export let data;

	const store = storeCtx.get();
	store.dispatch(hydrate(data));
	const readCurrenciesStore = useQuery(readCurrencies)(store)({});
	$: ({ data: currencies } = $readCurrenciesStore);
	const readAccountWalletStore = useQuery(readAccountWallet)(store)({});
	$: ({ data: wallet } = $readAccountWalletStore);
</script>

<a href="/">home</a>

<ol>
	{#each currencies?.ids ?? [] as currencyId}
		{@const currency = currencies?.entities[currencyId]}
		<li>
			<h3>
				{currency?.name}
				{wallet?.entities[currencyId]?.value ?? ''}
			</h3>
			<img alt={currency?.name} src={currency?.icon} />
			<p>
				{currency?.description}
			</p>
		</li>
	{/each}
</ol>
